cache:
  key: main-composer
  paths:
    - .cache

services:
  - name: docker:20.10-dind
    alias: docker

image: typo3/core-testing-docker:latest

stages:
  - composer
  - unit
#  - acceptance
#  - functional

composer:
  stage: composer
  script:
    - Build/Scripts/runTests.sh -s composerValidate -p 7.4
    - Build/Scripts/runTests.sh -s composerInstall -p 7.4

unit php 7.4:
  stage: unit
  script:
    - Build/Scripts/runTests.sh -s composerInstall -p 7.4
    - Build/Scripts/runTests.sh -s unit -p 7.4

unit php 8.0:
  stage: unit
  script:
    - Build/Scripts/runTests.sh -s composerInstall -p 8.0
    - Build/Scripts/runTests.sh -s unit -p 8.0