cache:
  key: main-composer
  paths:
    - .cache

services:
  - name: docker:20.10-dind
    alias: docker

image: typo3/core-testing-docker:latest

stages:
  - composer
#  - unit
#  - acceptance
#  - functional

composer:
  image: ubuntu-20.04
  stage: composer
  script:
    - Build/Scripts/runTests.sh -s composerValidate -p 7.4
    - Build/Scripts/runTests.sh -s composerInstall -p 7.4
