services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brix\CelumFal\Command\RefreshMetaCommand:
    tags:
      - name: 'console.command'
        command: 'celumfal:refreshmeta'

  Brix\CelumFal\Command\CompleteImportCommand:
    tags:
      - name: 'console.command'
        command: 'celumfal:completeimport'

  Brix\CelumFal\Index\Extractor:
    public: true

  Brix\CelumFal\Utility\HtmlResponse:
    public: true

  Brix\CelumFal\ToolbarItem\CumulusCacheCleanerItem:
    tags:
      - name: backend.toolbar.item
