services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brix\CelumFal\Command\RefreshMetaCommand:
    tags:
      - name: 'console.command'
        command: 'celumfal:refreshmeta'

  Brix\CelumFal\Command\CompleteImportCommand:
    tags:
      - name: 'console.command'
        command: 'celumfal:completeimport'

  Brix\CelumFal\Index\Extractor:
    public: true

  Brix\CelumFal\EventListener\ModifyClearCacheActionsEventListener:
    tags:
      - name: event.listener
        identifier: 'celum_fal-clear-cache-actions'